### ISSUE TITLE
Cursor should be pointer when hovering over answer options

### ISSUE THREAD

**Issue by sadidshaikh** [consci210/-Enkokilish-#13]
When hovering over the answer options, cursor is either 
**Text**
![text](https://user-images.githubusercontent.com/103301207/229980956-66a24ea2-3f97-4c7e-a337-d16b9c660fa8.PNG)
or 
**Default**
![default](https://user-images.githubusercontent.com/103301207/229981245-8cd83852-9b26-4cff-a301-d076588c9aa1.PNG)

I think it would be best if its
**Pointer**
![pointer](https://user-images.githubusercontent.com/103301207/229981317-e674487f-adfa-4bfb-adc0-206907b55320.PNG)

**Comment by sadidshaikh** [comment]
I would like to solve this, please assign @consci210

**Comment by consci210** [comment]
@sadidshaikh Nice, I like your attention to details .

**Comment by sadidshaikh** [comment]
Done
