### ISSUE TITLE
Create Login and Signup pages 

### ISSUE THREAD

**Issue by consci210** [consci210/-Enkokilish-#6]

**Comment by Mublin** [comment]
I will work on this @consci210

**Comment by consci210** [comment]
Sure

**Comment by Mublin** [comment]
> Sure

The theme color should be blue white and black right

**Comment by consci210** [comment]
I agree with the black and white , I am not sure about the blue though . Have a look at the other pages and if you think the three colors would be a good match to the rest of the content then sure you can go with those .

**Comment by Mublin** [comment]
> I agree with the black and white , I am not sure about the blue though . Have a look at the other pages and if you think the three colors would be a good match to the rest of the content then sure you can go with those .

Ok Thank you

**Comment by Mublin** [comment]
> I have approved your PR. Good Job .

Thank you, I really appreciated

**Comment by consci210** [comment]
@Mublin  🎉 I have added all the required functionalities to the login and signup forms . This means that any user can now create an account and login using their email and password 📧🔐 or simply use their Google account to authenticate.
